### ISSUE TITLE
Docker nvidia not installed even with kube_nvidia_support is true

### ISSUE THREAD

**Issue by enolfc** [grycap/ansible-role-kubernetes#142]
This seems to miss the `{{ }}` to work as expected:
https://github.com/grycap/ansible-role-kubernetes/blob/bb049dd7693cb0655d3bd0cb3b23af9000c24624/meta/main.yml#L36

**Comment by enolfc** [comment]
Also (although not directly related to this one repo):

when `nvidia_driver_ubuntu_install_from_cuda_repo` is set to true, some defaults are not working as expected, I had to adjust them as follows:
```
nvidia_driver_ubuntu_cuda_repo_gpgkey_url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/3bf863cc.pub"`
nvidia_driver_ubuntu_cuda_repo_gpgkey_id: "A4B469963BF863CC"
```

Even with those two fixed, the driver was not completely installed. Didn't look into details yet.

**Comment by micafer** [comment]
Hi @enolfc,

I tested and it seems to work fine. 
Could you test and confirm it?

**Comment by enolfc** [comment]
Just to confirm this seems to work fine now
