### ISSUE TITLE
Hey getting this error during play 

### ISSUE THREAD

**Issue by rafi494** [grycap/ansible-role-kubernetes#16]
TASK [grycap.kubernetes : Kubeadm init] *******************************************************************************************************
fatal: [server]: FAILED! => {"changed": true, "cmd": ["kubeadm", "init", "--pod-network-cidr=10.244.0.0/16", "--token=kube01.ubbxeuu2qn05zaqd"], "delta": "0:00:02.511056", "end": "2018-03-11 11:31:48.057528", "msg": "non-zero return code", "rc": 2, "start": "2018-03-11 11:31:45.546472", "stderr": "\t[WARNING FileExisting-crictl]: crictl not found in system path\n[preflight] Some fatal errors occurred:\n\t[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["\t[WARNING FileExisting-crictl]: crictl not found in system path", "[preflight] Some fatal errors occurred:", "\t[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "[init] Using Kubernetes version: v1.9.3\n[init] Using Authorization modes: [Node RBAC]\n[preflight] Running pre-flight checks.", "stdout_lines": ["[init] Using Kubernetes version: v1.9.3", "[init] Using Authorization modes: [Node RBAC]", "[preflight] Running pre-flight checks."]}

**Comment by rafi494** [comment]
Need to add task with below command 

echo "1"  > /proc/sys/net/bridge/bridge-nf-call-iptables

**Comment by micafer** [comment]
I cannot reproduce the error.
What O.S.  are you using?
What role options are you setting?
